---
title: "Homework Assignment 3"
author: "Vincent Xie"
toc: true
number-sections: true
highlight-style: pygments
format: 
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
---

# **NYC Rats** {.unnumbered}

Rats in NYC are widespread, as they are in many densely populated
areas (https://en.wikipedia.org
/wiki/Rats_in_New_York_City). As of 
October 2023, NYC dropped from the 2nd to the 3rd places in the 
annual ["rattiest city" list](https://www.orkin.com/press-room/top-rodent-infested-cities-2023#)
released by a pest control company. In 
the 311 Service Request Data, there is one complain type `Rodent`. 
Extract all the requests with complain type `Rodent`, created 
between January 1, 2022 and December 31, 2023. Save them into a 
csv file named `rodent_2022-2023.csv`.


**Data Initialization**

```{python}
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None

data = pd.read_csv("data/rodent_2022-2023.csv")
```

1. Are there any complains that are not closed yet?

```{python}
not_closed = data['Closed Date'].isna().sum()
not_closed
```

**Answer:** We see that there are 2,787 instances where the complaints have not been closed yet.

2. Are there any complains with a closed data before the created date?

```{python}
# Converting dates to datetime format for comparison
data['Created Date'] = pd.to_datetime(data['Created Date'], errors='coerce')
data['Closed Date'] = pd.to_datetime(data['Closed Date'], errors='coerce')
closed_before_created = data[data['Closed Date'] < data['Created Date']].shape[0]
closed_before_created
```

**Answer:** There are no instances where the closed data is before the created data. This is a good sign as it shows the date data makes sense.

3. How many agencies were this complain type reported to?

```{python}
unique_agencies = data['Agency'].nunique()
unique_agencies
```

**Answer:** There was only one unique Agency which was the Department of Health and Mental Hygiene (DOHMH).

4. Summarize the missingess for each variable.

```{python}
missingness_avg = data.isnull().mean().round(4) * 100
print("Average percentage of missing cells for each variable")
missingness_avg
```

**Answer:** From the table, there were many variables with a low missing percentage. The main variables with a high percentage were Facility Type, Due Date, Vehicle Type, Taxi Company Borough, Taxi Pick Up Location, Bridge Highway Name, Bridge Highway Direction, Road Ramp, and Bridge Highway Segment. A high percentage indicates that it was likely that the variable was not important to the overall dataset.

5. Summarize a frequency table for the DESCRIPTOR variable, and summarize a cross table by year.

```{python}
# Frequency table
descriptor_frequency = data['Descriptor'].value_counts()

# Cross Table by Year
data['Year'] = data['Created Date'].dt.year
descriptor_year_crosstab = pd.crosstab(data['Descriptor'], data['Year'])

print("Frequency Table\n", descriptor_frequency)
print("\nCross Table\n", descriptor_year_crosstab)
```

6. Which types of ‘DESCRIPTOR’ do you think should be included if our interest is rodent sighting?

**Answer:** If our interest is rodent sighting, the descriptors that should be included are "Mouse Sighting," "Rat Sighting," and possibly "Rodent Bite." The remaining descriptors "Signs of Rodents" and "Condition Attracting Rodents" do not specifically indicate that there was a rodent present.

7. Take a subset of the data with the descriptors you chose and summarize the response time by borough.

```{python}
# Creation of subset
selected = ['Rat Sighting', 'Mouse Sighting', 'Rodent Bite - PCS Only']
subset = data[data['Descriptor'].isin(selected)]

# Summarization
subset['Response Time'] = (subset['Closed Date'] - subset['Created Date']).dt.days
response_time = subset.groupby('Borough')['Response Time'].mean().round(2)
response_time
```

**Answer:** This analysis shows how Queens has one of the longest response times (in days) followed by Brooklyn. On the contrary, Bronx has the fastest response time with an average of 0.27 days. There is another variable called "Unspecified" which could indicate an unclosed complaint or another data errors.